export const GET_ADMIN_DATA_REQUEST = "GET_ADMIN_DATA_REQUEST";
export const GET_ADMIN_DATA_SUCCESS = "GET_ADMIN_DATA_SUCCESS";
export const GET_ADMIN_DATA_FAILURE= "GET_ADMIN_DATA_FAILURE";

//for adding DaADD
export const ADD_ADMIN_DATA_REQUEST = "ADD_ADMIN_DATA_REQUEST";
export const ADD_ADMIN_DATA_SUCCESS = "ADD_ADMIN_DATA_SUCCESS";
export const ADD_ADMIN_DATA_FAILURE= "ADD_ADMIN_DATA_FAILURE";

//for delete

export const DELETE_ADMIN_DATA_REQUEST  = 'DELETE_ADMIN_DATA_REQUEST'
export const DELETE_ADMIN_DATA_SUCCESS  = 'DELETE_ADMIN_DATA_SUCCESS'
export const DELETE_ADMIN_DATA_FAILURE  = 'DELETE_ADMIN_DATA_FAILURE'

//for update
export const UPDATE_ADMIN_DATA_REQUEST  = 'UPDATE_ADMIN_DATA_REQUEST'
export const UPDATE_ADMIN_DATA_SUCCESS  = 'UPDATE_ADMIN_DATA_SUCCESS'
export const UPDATE_ADMIN_DATA_FAILURE  = 'UPDATE_ADMIN_DATA_FAILURE'