export const GET_ADMIN_DATA_REQUEST = "GET_ADMIN_DATA_REQUEST";
export const GET_ADMIN_DATA_SUCCESS = "GET_ADMIN_DATA_SUCCESS";
export const GET_ADMIN_DATA_FAILURE= "GET_ADMIN_DATA_FAILURE";

//for adding DaADD
export const ADD_ADMIN_DATA_REQUEST = "ADD_ADMIN_DATA_REQUEST";
export const ADD_ADMIN_DATA_SUCCESS = "ADD_ADMIN_DATA_SUCCESS";
export const ADD_ADMIN_DATA_FAILURE= "ADD_ADMIN_DATA_FAILURE";

